spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql